# Generated by Django 3.1.1 on 2021-03-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210322_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('GREETING', 'greeting'), ('NEW_TEST', 'new_test')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
