# Generated by Django 3.1.1 on 2021-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('GREETING', 'greeting'), ('NEW_TEST', 'new_test'), ('NEW_USER', 'new_user')], max_length=8),
        ),
    ]
