# Generated by Django 3.1.1 on 2021-03-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvedquestion',
            name='right_answer',
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tests.question'),
            preserve_default=False,
        ),
    ]
