# Generated by Django 3.1.1 on 2021-06-10 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210324_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None),
        ),
    ]
