# Generated by Django 3.1.1 on 2020-10-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200913_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/tests/'),
        ),
    ]
