# Generated by Django 3.1.1 on 2020-10-11 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='test',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 11, 13, 36, 16, 762917)),
            preserve_default=False,
        ),
    ]
