# Generated by Django 3.1.1 on 2020-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20201011_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('CHECKBOXES', 'checkboxes'), ('RADIOS', 'radios')], default='TEXT', max_length=10),
        ),
    ]
