# Generated by Django 3.1.1 on 2020-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20201013_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers',
            new_name='answer_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers_type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('NUMBER', 'number'), ('CHECKBOXES', 'checkboxes'), ('RADIOS', 'radios')], default='TEXT', max_length=10),
        ),
    ]
