# Generated by Django 3.1.1 on 2020-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20201016_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='need_auth',
            field=models.BooleanField(default=True),
        ),
    ]
