# Generated by Django 3.1.1 on 2020-12-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_solvedquestion_solvedtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvedtest',
            old_name='questions',
            new_name='answers',
        ),
    ]
