# Generated by Django 3.1.1 on 2020-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20201208_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedtest',
            name='right_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solvedtest',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
