# Generated by Django 3.1.1 on 2020-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tests', '0012_auto_20201208_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(related_name='tests', to='tags.Tag'),
        ),
    ]
