# Generated by Django 3.1.1 on 2020-12-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20201215_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='solutions',
            field=models.IntegerField(default=0),
        ),
    ]
