# Generated by Django 3.1.1 on 2021-01-04 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_test_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedtest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 42, 1, 108111)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solvedtest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 42, 8, 274521)),
            preserve_default=False,
        ),
    ]
