# Generated by Django 3.1.1 on 2021-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tests', '0015_auto_20210104_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvedtest',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='tags.Tag'),
        ),
    ]
