# Generated by Django 3.1.1 on 2021-02-12 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0016_auto_20210212_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='disliked_users',
            field=models.ManyToManyField(related_name='disliked_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
