# Generated by Django 3.1.1 on 2021-02-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tests', '0018_auto_20210212_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(related_name='tests', to='tags.Tag'),
        ),
    ]
