# Generated by Django 3.1.1 on 2021-02-17 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('tests', '0019_auto_20210212_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tests', to='tags.Tag'),
        ),
    ]
