# Generated by Django 3.1.1 on 2021-03-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20210217_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvedtest',
            options={'ordering': ['-date_ended']},
        ),
        migrations.RenameField(
            model_name='solvedtest',
            old_name='end_date',
            new_name='date_ended',
        ),
        migrations.RenameField(
            model_name='solvedtest',
            old_name='start_date',
            new_name='date_started',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='need_auth',
            new_name='needs_auth',
        ),
        migrations.RemoveField(
            model_name='solvedtest',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='solvedtest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='test',
            name='solutions',
        ),
        migrations.AddField(
            model_name='solvedtest',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tests.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('NUMBER', 'number'), ('RADIOS', 'radios')], default='TEXT', max_length=10),
        ),
    ]
