# Generated by Django 3.1.1 on 2021-03-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_auto_20210320_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedtest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tests.test'),
        ),
    ]
