# Generated by Django 3.1.1 on 2021-03-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_auto_20210320_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedtest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tests.test'),
        ),
    ]
