# Generated by Django 3.1.1 on 2021-03-20 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0025_auto_20210320_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedtest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solved_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
